CREATE TABLE IF NOT EXISTS enemy_ais (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT DEFAULT '',
  filename VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  uploaded_by INT DEFAULT NULL,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 1,
  file_size INT NOT NULL DEFAULT 0,
  FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
);
