DROP TABLE IF EXISTS admin_actions;
DROP TABLE IF EXISTS user_stats;
DROP TABLE IF EXISTS match_players;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS login_attempts;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS users;
