ALTER TABLE users ADD COLUMN is_banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN ban_reason VARCHAR(500) DEFAULT NULL;
ALTER TABLE users ADD COLUMN display_name VARCHAR(30) NOT NULL DEFAULT '';
